### ISSUE TITLE
Support custom Caddy download URLs

### ISSUE THREAD

**Issue by babolivier** [atosatto/ansible-caddy#4]
Hey, and thanks for this amazing work!

I'd like to install caddy with plugins. I think the best and easiest way to do that would be to allow the playbook's author to specify a custom URL to caddy's binaries (such as `https://caddyserver.com/download/linux/amd64?plugins=http.git&license=personal&telemetry=off` in my example).

What do you think about that?

**Comment by atosatto** [comment]
Hey @babolivier thanks for the very nice feedback! :)

> I'd like to install caddy with plugins. I think the best and easiest way to do that would be to allow the playbook's author to specify a custom URL to caddy's binaries (such as https://caddyserver.com/download/linux/amd64?plugins=http.git&license=personal&telemetry=off in my example).

I was thinking about something similar too! Would you like to contribute that with a PR? ;)

**Comment by babolivier** [comment]
Sure! I'll look into it once I find some time :)

**Comment by atosatto** [comment]
Ehi @babolivier, in case you are still interested in downloading Caddy using a custom download URL, this has been now implemented in #5.
All that you need to do is setting the `caddy_download_url` variable to the custom download URL.

Feel free to post any additional comment, suggestion and feedback. :)

**Comment by babolivier** [comment]
Hey @atosatto, awesome, thanks, I'll try it out! Sorry for not finding time to PR it!

**Comment by atosatto** [comment]
No problem! Thanks for suggesting this very valuable feature.
This is now part of the `v1.1.0` release of the role.
